### ISSUE TITLE
Eskimo without MongoDB and Redis

### ISSUE THREAD

**Issue by vishtahil** [glazedio/glazed#116]
I am want to use Eskimo boilerplate application to connect to another no-sql database instead of MongoDB and Redis. How can I remove the dependencies of MongoDb and other features which I do not want?. I removed MongoDB entires from package.json but "node app" command fails... Please help!

**Comment by BrunoBernardino** [comment]
This is not something we're currently interested in supporting officially,
because the generator commands and other parts rely on mongoose and redis.
If you want to change those, you'll have to go through the code to find
where they're linked.

I'd suggest looking in the models, boot directory, and igloo, since I
believe it looks for redis in sessions (not near a computer now).

Those should be enough, but again, you won't be able to use the commands
for generating models or controllers without mongoose.
On Mon 8 Jun 2015 at 21:15 vijrej <notifications@github.com> wrote:

> I am want to use Eskimo boilerplate application to connect to another
> no-sql database instead of MongoDB and Redis. How can I remove the
> dependencies of MongoDb and other features which I do not want?. I removed
> MongoDB entires from package.json but "node app" command fails... Please
> help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niftylettuce/eskimo/issues/116>.
>
-- 
http://brunobernardino.com
